# Generated by Django 4.1.4 on 2022-12-27 06:40

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(upload_to=product.models.upload_path),
        ),
    ]
