# Generated by Django 4.1.4 on 2022-12-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("seller", "seller"), ("buyer", "buyer")],
                max_length=20,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
