# Generated by Django 4.1.4 on 2022-12-28 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="product name")),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator],
                        verbose_name="price",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        verbose_name="quantity of purchased"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("processing", "processing"),
                            ("canceled", "canceled"),
                            ("on hold", "on hold"),
                            ("refunded", "refunded"),
                            ("placed", "placed"),
                        ],
                        default="placed",
                        max_length=50,
                        verbose_name="order status",
                    ),
                ),
                (
                    "date_placed",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date ordered"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="product_id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
